name: Deploy to ACR

on:
  push:
    branches:
      - main
    # paths:
    #   - 'stadium-app/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.ACR_SERVER }}/backend
      BUILD_PATH: .
      DOCKERFILE_PATH: .dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate build ID
        id: tag
        run: |
          echo "BUILD_ID=$(TZ='Asia/Taipei' date +"%Y%m%d.%H%M%S")" >> $GITHUB_ENV

      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ env.BUILD_PATH }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.BUILD_ID }}
          file: ${{ env.DOCKERFILE_PATH }}
            
      - name: Save container hashes
        id: acr
        run: |
            echo "$(docker inspect ${{ env.IMAGE_NAME }}:latest -f '{{ .Id }}')" >> acr.txt